import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "@/lib/Provider";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import ReduxProvider from "@/lib/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZStore - Home",
  description: "Generated by create next app",
  icons: {
    icon: ["/favicon.ico?v=4"],
  },
  manifest: "/site.webmanifest",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReduxProvider>
      <html lang="en" data-theme="light">
        <body className={poppins.className}>
          <Navbar></Navbar>
          <Providers>{children}</Providers>
          <Footer></Footer>
        </body>
      </html>
    </ReduxProvider>
  );
}
